//! Blinc runtime substrate.
//!
//! Runtime-agnostic plumbing shared by the JIT path (the
//! `blinc_dsl_core` crate, which compiles `.blinc` source through
//! Zyntax+Cranelift in-process) and the AOT path (a future
//! per-app crate generated by Zyntax+LLVM at build time). Both
//! produce the same surface: a set of callable symbols + a pure-
//! data FSM registry. This crate is what consumes that surface
//! and bridges it to widget-side machinery (`Stateful<S>`).
//!
//! The headline module is [`fsm`] — see its docs for the
//! architecture diagram.

pub mod component;
pub mod fsm;
pub mod reactive_value;
pub mod reload;
pub mod signal;
pub mod view;

// Convenience re-exports — `Reactive<T>` is the first DSL value
// type and lives at the top of every consumer's import list.
pub use reactive_value::{
    REACTIVE_TAG_COMPUTED, REACTIVE_TAG_LITERAL, REACTIVE_TAG_SIGNAL, Reactive,
};

// `ZyntaxValue` is the canonical runtime value representation
// — JIT and AOT compiled code from Zyntax both produce it.
// Re-exported here so the substrate's surface includes the
// value enum without callers needing to depend on
// `zyntax_embed` themselves.
pub use zyntax_embed::ZyntaxValue;

pub use blinc_layout;

pub use blinc_core;

#[cfg(feature = "blinc_animation")]
pub use blinc_animation;

#[cfg(feature = "blinc_gpu")]
pub use blinc_gpu;

#[cfg(feature = "blinc_paint")]
pub use blinc_paint;

// #[cfg(feature = "blinc_cn")]
// pub use blinc_cn;

/// Initialize the Blinc runtime
pub fn init() -> anyhow::Result<()> {
    Ok(())
}
